=== JovanMihic/NRT_117_18/OglasiServis/Oglasi.dtd
<!ELEMENT OglasiLista (Oglas*)>
<!ELEMENT Oglas (Kategorija,DatumIsteka,Cena,Tekst,Oznaka*,E-mail+)>
<!ELEMENT Kategorija (#PCDATA)>
<!ELEMENT DatumIsteka (#PCDATA)>
<!ELEMENT Cena (#PCDATA)>
<!ELEMENT Tekst (#PCDATA)>
<!ELEMENT Oznaka (#PCDATA)>
<!ELEMENT E-mail (#PCDATA)>

<!ATTLIST OglasiLista noNamespaceSchemaLocation CDATA #REQUIRED>    
<!ATTLIST Cena valuta (rsd|eur|usd) "rsd">

=== JovanMihic/NRT_117_18/OglasiServis/Oglasi.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE OglasiLista SYSTEM "Oglasi.dtd">
<OglasiLista noNamespaceSchemaLocation="Oglasi.xsd">
    <Oglas>
        <Kategorija>Automobili</Kategorija>
        <DatumIsteka>2022-11-16</DatumIsteka>
        <Cena valuta="eur">1300</Cena>
        <Tekst>Automobil Opel Astra 2006. godiste na prodaju</Tekst>
        <Oznaka>Polovno</Oznaka>
        <Email>miki.mikic@gmlsi.com</Email>
        <Email>miki.krnjaca@gmlsi.com</Email>
    </Oglas>
    <Oglas>
        <Kategorija>Stanovi</Kategorija>
        <DatumIsteka>2022-12-06</DatumIsteka>
        <Cena valuta="eur">300</Cena>
        <Tekst>Trosoban stan na Mirijevu 50 kvadrata, 300e mesecno</Tekst>
        <Oznaka>Novogradnja</Oznaka>
        <Oznaka>Izdavanje</Oznaka>
        <Email>stefan.mirijevo@yahsio.com</Email>
    </Oglas>
    <Oglas>
        <Kategorija>Konzole i igrice</Kategorija>
        <DatumIsteka>2022-08-02</DatumIsteka>
        <Cena valuta="rsd">18000</Cena>
        <Tekst>Sony Playstation 3, slabo koriscen u odlicnom stanju, sa dzojsticima i kablovima</Tekst>
        <Oznaka>Polovno</Oznaka>
        <Oznaka>Kao novo</Oznaka>
        <Email>djole.sony011@oepmnnsdn.com</Email>
    </Oglas>
</OglasiLista>
